- id: doi:10.1186/s12859-023-05341-w
  buttons:
    - type: source
      link: https://github.com/DamianJM/Depolymerase-Predictor
    - type: website
      link: https://timskvortsov.github.io/WebDePP/
  image: https://timskvortsov.github.io/WebDePP/assets/DePP.png

- id: pmid:22649654
  date: '2010-01-01'

- id: pmc:PMC3695354
  date: '2013-01-01'

- id: isbn:9781119434498
  authors:
    - Timofey Skvortsov
    - Jean-Yves Maillard
  link: https://www.wiley.com/en-ie/Hugo+and+Russell's+Pharmaceutical+Microbiology,+9th+Edition-p-9781119434559
  date: '2023-01-01'
