name: build-preview
run-name: build pull request preview

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

# variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      # for debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      
      

#TS added start; rbenv fix attempt
      - name: Install Ruby to $RUNNER_TOOL_CACHE
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libssl-dev libreadline-dev zlib1g-dev
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(~/.rbenv/bin/rbenv init -)"
          ~/.rbenv/plugins/ruby-build/bin/ruby-build 3.3.0 /opt/hostedtoolcache/Ruby/3.3.0/x64
          touch /opt/hostedtoolcache/Ruby/3.3.0/x64.complete
          export PATH="/opt/hostedtoolcache/Ruby/3.3.0/x64/bin:$PATH"
          ruby -v

      - name: Install Bundler (user install, safe for all runners)
        run: |
          gem install bundler --user-install
          export PATH="$HOME/.gem/ruby/3.3.0/bin:$PATH"
          bundler -v

      - name: Install dependencies with Bundler
        run: |
          export PATH="$HOME/.gem/ruby/3.3.0/bin:$PATH"
          bundle install --jobs 4 --retry 3
 #TS added end    


      - name: Get Pages url
        if: github.event.action != 'closed'
        id: pages
        uses: actions/configure-pages@v4

      # for debugging
      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Build preview version of site
        if: github.event.action != 'closed'
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.number }}"

      - name: Commit preview to Pages branch
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: _site
          umbrella-dir: ${{ env.PREVIEWS_FOLDER }}
